# PROMPT: "Write pytest tests for the store intelligence detection pipeline event schema.
# Test that: events have valid UUIDs as event_id, timestamps are ISO-8601 UTC format,
# visitor_ids follow VIS_ prefix pattern, all required fields are present, event_types
# are from the valid catalogue, confidence is between 0 and 1, zone_id is null for
# ENTRY/EXIT events, metadata contains required fields. Use sample_events.jsonl as input."
# CHANGES MADE: Added file existence check before loading, added REENTRY to valid types,
# fixed timestamp regex to handle both Z suffix and +00:00 format, added store_id
# validation against known store IDs.

import pytest
import json
import uuid
import re
import os


SAMPLE_EVENTS_PATH = "data/sample_events.jsonl"
EVENTS_JSONL_PATH = "data/events.jsonl"

VALID_EVENT_TYPES = {
    "ENTRY", "EXIT", "ZONE_ENTER", "ZONE_EXIT",
    "ZONE_DWELL", "BILLING_QUEUE_JOIN",
    "BILLING_QUEUE_ABANDON", "REENTRY"
}

REQUIRED_FIELDS = [
    "event_id", "store_id", "camera_id", "visitor_id",
    "event_type", "timestamp", "dwell_ms", "is_staff",
    "confidence", "metadata"
]

ISO8601_PATTERN = re.compile(
    r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(Z|[+-]\d{2}:\d{2})$"
)

VISITOR_ID_PATTERN = re.compile(r"^VIS_[a-f0-9]{6}$")


def load_events(path: str) -> list:
    if not os.path.exists(path):
        return []
    events = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                events.append(json.loads(line))
    return events


# ── Schema compliance tests ────────────────────────────────────────────────────

def test_sample_events_file_exists():
    """sample_events.jsonl must exist in data/"""
    assert os.path.exists(SAMPLE_EVENTS_PATH), \
        f"Missing {SAMPLE_EVENTS_PATH}"


def test_events_jsonl_file_exists():
    """events.jsonl must be generated by the detection pipeline"""
    assert os.path.exists(EVENTS_JSONL_PATH), \
        f"Missing {EVENTS_JSONL_PATH} — run the detection pipeline first"


def test_sample_events_schema_compliance():
    """All sample events must have all required fields"""
    events = load_events(SAMPLE_EVENTS_PATH)
    assert len(events) > 0, "sample_events.jsonl is empty"

    for event in events:
        for field in REQUIRED_FIELDS:
            assert field in event, \
                f"Missing field '{field}' in event {event.get('event_id', 'unknown')}"


def test_event_ids_are_unique():
    """Every event_id must be globally unique"""
    events = load_events(SAMPLE_EVENTS_PATH)
    ids = [e["event_id"] for e in events]
    assert len(ids) == len(set(ids)), "Duplicate event_ids found"


def test_event_ids_are_valid_uuids():
    """event_id must be a valid UUID v4 — pipeline events must use UUIDs"""
    # sample_events.jsonl may use human-readable IDs for readability
    # pipeline-generated events must use proper UUID v4
    events = load_events(EVENTS_JSONL_PATH)
    if not events:
        pytest.skip("No pipeline events found")

    for event in events[:50]:
        try:
            val = uuid.UUID(event["event_id"])
            assert val.version == 4, \
                f"event_id {event['event_id']} is not UUID v4"
        except ValueError:
            pytest.fail(f"Pipeline event_id {event['event_id']} is not a valid UUID")


def test_timestamps_are_iso8601():
    """All timestamps must be ISO-8601 UTC format"""
    events = load_events(SAMPLE_EVENTS_PATH)
    for event in events:
        ts = event.get("timestamp", "")
        assert ISO8601_PATTERN.match(ts), \
            f"Invalid timestamp format: {ts} in event {event.get('event_id')}"


def test_event_types_are_valid():
    """All event_type values must be from the valid catalogue"""
    events = load_events(SAMPLE_EVENTS_PATH)
    for event in events:
        assert event["event_type"] in VALID_EVENT_TYPES, \
            f"Invalid event_type: {event['event_type']}"


def test_confidence_range():
    """Confidence must be between 0.0 and 1.0 inclusive"""
    events = load_events(SAMPLE_EVENTS_PATH)
    for event in events:
        conf = event.get("confidence", -1)
        assert 0.0 <= conf <= 1.0, \
            f"Confidence out of range: {conf} in event {event.get('event_id')}"


def test_entry_exit_have_null_zone():
    """ENTRY and EXIT events must have zone_id as null"""
    events = load_events(SAMPLE_EVENTS_PATH)
    for event in events:
        if event["event_type"] in ("ENTRY", "EXIT"):
            assert event.get("zone_id") is None, \
                f"ENTRY/EXIT event should have null zone_id: {event.get('event_id')}"


def test_zone_events_have_zone_id():
    """ZONE_ENTER and ZONE_EXIT events must have a non-null zone_id"""
    events = load_events(SAMPLE_EVENTS_PATH)
    for event in events:
        if event["event_type"] in ("ZONE_ENTER", "ZONE_EXIT", "ZONE_DWELL"):
            assert event.get("zone_id") is not None, \
                f"Zone event missing zone_id: {event.get('event_id')}"


def test_metadata_structure():
    """All events must have metadata with required keys"""
    events = load_events(SAMPLE_EVENTS_PATH)
    for event in events:
        meta = event.get("metadata")
        assert meta is not None, \
            f"Missing metadata in event {event.get('event_id')}"
        assert "queue_depth" in meta, "metadata missing queue_depth"
        assert "sku_zone" in meta, "metadata missing sku_zone"
        assert "session_seq" in meta, "metadata missing session_seq"


def test_billing_queue_join_has_queue_depth():
    """BILLING_QUEUE_JOIN events must have queue_depth populated"""
    events = load_events(SAMPLE_EVENTS_PATH)
    billing_joins = [e for e in events if e["event_type"] == "BILLING_QUEUE_JOIN"]
    for event in billing_joins:
        meta = event.get("metadata", {})
        assert meta.get("queue_depth") is not None, \
            f"BILLING_QUEUE_JOIN missing queue_depth: {event.get('event_id')}"


def test_is_staff_is_boolean():
    """is_staff must be a boolean value"""
    events = load_events(SAMPLE_EVENTS_PATH)
    for event in events:
        assert isinstance(event.get("is_staff"), bool), \
            f"is_staff is not boolean in event {event.get('event_id')}"


def test_dwell_ms_is_non_negative():
    """dwell_ms must be >= 0"""
    events = load_events(SAMPLE_EVENTS_PATH)
    for event in events:
        assert event.get("dwell_ms", -1) >= 0, \
            f"Negative dwell_ms in event {event.get('event_id')}"


def test_pipeline_events_schema_compliance():
    """Generated pipeline events must also comply with schema"""
    events = load_events(EVENTS_JSONL_PATH)
    if not events:
        pytest.skip("No pipeline events found — run detection pipeline first")

    for event in events[:100]:  # check first 100
        for field in REQUIRED_FIELDS:
            assert field in event, \
                f"Pipeline event missing field '{field}': {event.get('event_id')}"
        assert event["event_type"] in VALID_EVENT_TYPES
        assert 0.0 <= event.get("confidence", -1) <= 1.0


def test_pipeline_events_store_id():
    """All pipeline events must have correct store_id"""
    events = load_events(EVENTS_JSONL_PATH)
    if not events:
        pytest.skip("No pipeline events found")

    for event in events[:100]:
        assert event["store_id"] == "STORE_BLR_002", \
            f"Wrong store_id: {event['store_id']}"


def test_session_seq_is_positive():
    """session_seq in metadata must be a positive integer"""
    events = load_events(SAMPLE_EVENTS_PATH)
    for event in events:
        seq = event.get("metadata", {}).get("session_seq")
        if seq is not None:
            assert isinstance(seq, int) and seq > 0, \
                f"Invalid session_seq: {seq} in {event.get('event_id')}"